# =============================================================================
# build_data_dictionary_skeleton.R
#
# Lists every table in data/ (parquet) and output/ (csv) with its column names
# and types, and writes docs/data_dictionary_skeleton.md with an empty
# "Description" column to fill in by hand. Reads schemas / first rows only,
# so it is fast even on the large cached files.
#
# Run from the project root:  source("docs/build_data_dictionary_skeleton.R")
# =============================================================================

library(here)
library(arrow)
library(readr)

describe_parquet <- function(path) {
  sch <- arrow::open_dataset(path)$schema
  data.frame(column = names(sch),
             type = vapply(sch$fields, function(f) f$type$ToString(), character(1)),
             stringsAsFactors = FALSE)
}

describe_csv <- function(path) {
  x <- readr::read_csv(path, n_max = 1000, show_col_types = FALSE, progress = FALSE)
  data.frame(column = names(x),
             type = vapply(x, function(col) class(col)[1], character(1)),
             stringsAsFactors = FALSE)
}

section <- function(rel_path, info) {
  c(paste0("### `", rel_path, "`"), "",
    "| Column | Type | Description |", "|---|---|---|",
    paste0("| `", info$column, "` | ", info$type, " | TODO |"), "")
}

files <- c(
  list.files(here("data"),   pattern = "\\.parquet$", recursive = TRUE, full.names = TRUE),
  list.files(here("output"), pattern = "\\.csv$",     recursive = TRUE, full.names = TRUE)
)

lines <- c("# Data dictionary skeleton", "",
           "Generated by `docs/build_data_dictionary_skeleton.R`. Fill in each Description.", "")

for (f in sort(files)) {
  rel <- sub(paste0("^", here(), "/?"), "", f)
  info <- tryCatch(
    if (grepl("\\.parquet$", f)) describe_parquet(f) else describe_csv(f),
    error = function(e) NULL
  )
  if (is.null(info)) {
    lines <- c(lines, paste0("### `", rel, "`"), "", "_Could not read this file._", "")
  } else {
    lines <- c(lines, section(rel, info))
  }
}

writeLines(lines, here("docs", "data_dictionary_skeleton.md"))
message("Wrote docs/data_dictionary_skeleton.md (", length(files), " files)")
